

services:

  server:
    build:
      context: ./server/
    expose:
      - 8000
    ports:
      - 8000:8000
    init: true

  client:
    build:
      context: ./client/
    expose:
      - 8001
    ports:
      - 8001:8000
    links:
        - server
    init: true

