

services:

  server_test:
    build:
      context: ./server_test/
    environment:
      URI_SERVER: http://server:8000
    links:
        - server

  client_test:
    #build:
    #  context: ./client_test/
    image: cypress/included:8.3.0
    links:
        - client
