name: Client Test

on:
  push:
    paths:
      - 'client/**'
      - 'client_test/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and Test
      run: make test_client
