name: Client Test Example

on:
  push:
    paths:
      - 'client_example/**'
      - 'client_test/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # Temp Disable on CI - the cypress container is 3GB
    #- name: Build and Test
    #  run: make test_example_client
