name: server

on:
  push:
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      
      - name: make build
        run: make build

      - name: make test
        run: make test
