name: Server

on:
  push:
    paths:
      - 'server/**'

defaults:
  run:
    working-directory: server

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build
      run: make build
    - name: Test
      run: make test
