name: Server Test Example

on:
  push:
    paths:
      - 'server_example/**'
      - 'server_test/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Build and Test
      run: make test_example_server
