name: test_client

on:
  #- workflow_dispatch  # Disable running on every commit because this job downloaded a 4gb image and github actions 
  push:
    paths:
      - '.git/workflows/test_example_client.yml'
      - 'client/**'
      - 'test_client/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    # Temp Disable on CI - the cypress container is 3GB
    #- name: Build and Test
    #  run: make test_client
